# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-23 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastUpdate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionBibliographyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseNumber', models.CharField(default='', max_length=16)),
                ('DecisionDate', models.DateField(blank=True, null=True)),
                ('OnlineDate', models.DateField(blank=True, null=True)),
                ('Applicant', models.CharField(default='', max_length=50)),
                ('Opponents', models.CharField(default='', max_length=200)),
                ('Appellants', models.CharField(default='', max_length=200)),
                ('Respondents', models.CharField(default='', max_length=200)),
                ('ApplicationNumber', models.CharField(default='', max_length=15)),
                ('IPC', models.CharField(default='', max_length=50)),
                ('Title', models.TextField(default='')),
                ('ProcedureLanguage', models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('FR', 'FR')], default='', max_length=2)),
                ('Board', models.CharField(default='', max_length=16)),
                ('Keywords', models.TextField(default='')),
                ('Articles', models.CharField(default='', max_length=100)),
                ('Rules', models.CharField(default='', max_length=100)),
                ('ECLI', models.CharField(default='', max_length=20)),
                ('CitedCases', models.CharField(default='', max_length=700)),
                ('Distribution', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('', 'unknown')], default='', max_length=1)),
                ('Headword', models.CharField(default='', max_length=100)),
                ('Catchwords', models.TextField(default='')),
                ('DecisionLanguage', models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('FR', 'FR')], default='', max_length=2)),
                ('Link', models.URLField(default='', max_length=100)),
                ('PDFLink', models.URLField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DecisionTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FactsHeader', models.TextField(default='')),
                ('Facts', models.TextField(default='')),
                ('ReasonsHeader', models.TextField(default='')),
                ('Reasons', models.TextField(default='')),
                ('OrderHeader', models.TextField(default='')),
                ('Order', models.TextField(default='')),
                ('Language', models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('FR', 'FR')], default='', max_length=2)),
                ('HasSplitText', models.BooleanField(default=False)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Decisions.DecisionBibliographyModel')),
            ],
        ),
        migrations.CreateModel(
            name='BoardAnalysisModel',
            fields=[
                ('analysismodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Decisions.AnalysisModel')),
                ('Board', models.CharField(default='', max_length=16)),
                ('Count', models.IntegerField(default=0)),
                ('EarliestFive', models.CharField(max_length=50)),
                ('LatestFive', models.CharField(max_length=50)),
                ('IPC_TopFive', models.CharField(default='', max_length=120)),
                ('Article_TopFive', models.CharField(default='', max_length=120)),
                ('Cited_TopFive', models.CharField(default='', max_length=120)),
                ('Timeline', models.TextField(default='')),
            ],
            bases=('Decisions.analysismodel',),
        ),
    ]
