# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-25 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NullBibliographyModel',
            fields=[
                ('decisionbibliographymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Decisions.DecisionBibliographyModel')),
            ],
            bases=('Decisions.decisionbibliographymodel',),
        ),
        migrations.CreateModel(
            name='NullTextModel',
            fields=[
                ('decisiontextmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Decisions.DecisionTextModel')),
            ],
            bases=('Decisions.decisiontextmodel',),
        ),
        migrations.RenameField(
            model_name='decisiontextmodel',
            old_name='decision',
            new_name='Bibliography',
        ),
    ]
