# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-07 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0002_auto_20170125_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionSupplementaryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExtraCasesExtractedFromTexts', models.CharField(default='', max_length=700)),
                ('CitedCasesNotFoundInTexts', models.CharField(default='', max_length=700)),
                ('CitingCases', models.CharField(default='', max_length=700)),
                ('Bibliography', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Decisions.DecisionBibliographyModel')),
            ],
        ),
    ]
