# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-13 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0006_auto_20170213_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionsupplementarymodel',
            name='CitingCases',
        ),
        migrations.AddField(
            model_name='decisionsupplementarymodel',
            name='CitingCases',
            field=models.ManyToManyField(related_name='CitingCases', to='Decisions.DecisionBibliographyModel'),
        ),
    ]
