# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0007_auto_20170213_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionsupplementarymodel',
            name='CitingCases',
        ),
        migrations.AddField(
            model_name='decisionsupplementarymodel',
            name='CitingCases_DB',
            field=models.ManyToManyField(related_name='CitingCases_DB', to='Decisions.DecisionBibliographyModel'),
        ),
        migrations.AddField(
            model_name='decisionsupplementarymodel',
            name='CitingCases_Text',
            field=models.ManyToManyField(related_name='CitingCases_Text', to='Decisions.DecisionBibliographyModel'),
        ),
        migrations.AlterField(
            model_name='decisionsupplementarymodel',
            name='Bibliography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Decisions.DecisionBibliographyModel'),
        ),
    ]
