# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0008_auto_20170215_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decisionsupplementarymodel',
            old_name='CitingCases_DB',
            new_name='CitingCases_Bibliography',
        ),
    ]
