# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0009_auto_20170215_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionsupplementarymodel',
            name='Bibliography',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Decisions.DecisionBibliographyModel'),
        ),
    ]
