# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0010_auto_20170215_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontextmodel',
            name='Bibliography',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Decisions.DecisionBibliographyModel'),
        ),
    ]
