# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0014_auto_20170216_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionsupplementarymodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='decisionsupplementarymodel',
            name='Bibliography',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='SupplementModel', serialize=False, to='Decisions.DecisionBibliographyModel'),
        ),
    ]
