# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0015_auto_20170216_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionsupplementarymodel',
            name='CitedCases_InDB_NotInTexts',
        ),
    ]
