# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Decisions', '0016_remove_decisionsupplementarymodel_citedcases_indb_notintexts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecisionSupplementaryModel',
        ),
        migrations.DeleteModel(
            name='NullSupplementaryModel',
        ),
    ]
