# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160912_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionbibliographymodel',
            name='DecisionLanguage',
            field=models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('FR', 'FR')], default='', max_length=2),
        ),
    ]
