# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_decisionbibliographymodel_decisionlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionTextModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FactsHeader', models.TextField(default='')),
                ('Facts', models.TextField(default='')),
                ('ReasonsHeader', models.TextField(default='')),
                ('Reasons', models.TextField(default='')),
                ('OrderHeader', models.TextField(default='')),
                ('Order', models.TextField(default='')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.DecisionBibliographyModel')),
            ],
        ),
    ]
