# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20161010_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAnalysisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Board', models.CharField(default='', max_length=16)),
                ('IPC_TopFive', models.CharField(default='', max_length=50)),
                ('Article_TopFive', models.CharField(default='', max_length=50)),
                ('Cited_TopFive', models.CharField(default='', max_length=80)),
                ('LastUpdate', models.DateField(auto_now=True)),
            ],
        ),
    ]
