# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20161011_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineAnalysisModel',
            fields=[
                ('analysismodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AnalysisModel')),
                ('BibliographyCount', models.IntegerField()),
                ('Boards', models.TextField(default='')),
                ('Timelines', models.TextField(default='')),
            ],
            bases=('app.analysismodel',),
        ),
    ]
