# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20161012_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardanalysismodel',
            name='Count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boardanalysismodel',
            name='Earliest',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='boardanalysismodel',
            name='Latest',
            field=models.CharField(default='', max_length=10),
        ),
    ]
