# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20161012_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardanalysismodel',
            name='Earliest',
        ),
        migrations.RemoveField(
            model_name='boardanalysismodel',
            name='Latest',
        ),
        migrations.AddField(
            model_name='boardanalysismodel',
            name='EarliestCaseNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='boardanalysismodel',
            name='EarliestDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boardanalysismodel',
            name='LatestCaseNumber',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='boardanalysismodel',
            name='LatestDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
