# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20161014_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardanalysismodel',
            name='EarliestCaseNumber',
        ),
        migrations.RemoveField(
            model_name='boardanalysismodel',
            name='EarliestDate',
        ),
        migrations.RemoveField(
            model_name='boardanalysismodel',
            name='LatestCaseNumber',
        ),
        migrations.RemoveField(
            model_name='boardanalysismodel',
            name='LatestDate',
        ),
        migrations.AlterField(
            model_name='boardanalysismodel',
            name='EarliestFive',
            field=models.CharField(max_length=50),
        ),
    ]
