# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20161014_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardanalysismodel',
            name='LatestFive',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
