# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionBibliographyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseNumber', models.CharField(default='', max_length=16)),
                ('DecisionDate', models.DateField(blank=True, null=True)),
                ('OnlineDate', models.DateField(blank=True, null=True)),
                ('Applicant', models.CharField(default='', max_length=50)),
                ('Opponents', models.CharField(default='', max_length=200)),
                ('Appellants', models.CharField(default='', max_length=200)),
                ('Respondents', models.CharField(default='', max_length=200)),
                ('ApplicationNumber', models.CharField(default='', max_length=15)),
                ('IPC', models.CharField(default='', max_length=50)),
                ('Title', models.TextField(default='')),
                ('ProcedureLanguage', models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('FR', 'FR')], default='', max_length=2)),
                ('Board', models.CharField(default='', max_length=16)),
                ('Keywords', models.TextField(default='')),
                ('Articles', models.CharField(default='', max_length=100)),
                ('Rules', models.CharField(default='', max_length=100)),
                ('ECLI', models.CharField(default='', max_length=20)),
                ('CitedCases', models.CharField(default='', max_length=700)),
                ('Distribution', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=1)),
                ('Headword', models.CharField(default='', max_length=100)),
                ('Catchwords', models.TextField(default='')),
                ('LinkDE', models.URLField(default='', max_length=100)),
                ('LinkEN', models.URLField(default='', max_length=100)),
                ('LinkFR', models.URLField(default='', max_length=100)),
                ('PDFLink', models.URLField(default='', max_length=100)),
            ],
        ),
    ]
