# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_decisiontextmodel_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionbibliographymodel',
            name='Link',
            field=models.URLField(default='', max_length=100),
        ),
    ]
