# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_boardanalysismodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastUpdate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='boardanalysismodel',
            name='LastUpdate',
        ),
        migrations.RemoveField(
            model_name='boardanalysismodel',
            name='id',
        ),
        migrations.AddField(
            model_name='boardanalysismodel',
            name='analysismodel_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AnalysisModel'),
            preserve_default=False,
        ),
    ]
