# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_timelineanalysismodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelineanalysismodel',
            name='analysismodel_ptr',
        ),
        migrations.AddField(
            model_name='boardanalysismodel',
            name='Timeline',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='TimelineAnalysisModel',
        ),
    ]
