# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographyBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CaseNumber', models.CharField(default='', max_length=16)),
                ('DecisionDate', models.DateField(blank=True, null=True)),
                ('OnlineDate', models.DateField(blank=True, null=True)),
                ('Applicant', models.CharField(default='', max_length=50)),
                ('Opponents', models.CharField(default='', max_length=200)),
                ('Appellants', models.CharField(default='', max_length=200)),
                ('Respondents', models.CharField(default='', max_length=200)),
                ('ApplicationNumber', models.CharField(default='', max_length=15)),
                ('IPC', models.CharField(default='', max_length=50)),
                ('ProcedureLanguage', models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('FR', 'FR')], default='', max_length=2)),
                ('Board', models.CharField(default='', max_length=16)),
                ('Articles', models.CharField(default='', max_length=100)),
                ('Rules', models.CharField(default='', max_length=100)),
                ('ECLI', models.CharField(default='', max_length=20)),
                ('CitedCases', models.CharField(default='', max_length=700)),
                ('Distribution', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('', 'unknown')], default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BibliographyLanguageVersionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DecisionLanguage', models.CharField(choices=[('DE', 'DE'), ('EN', 'EN'), ('FR', 'FR')], default='', max_length=2)),
                ('Title', models.TextField(default='')),
                ('Keywords', models.TextField(default='')),
                ('Headword', models.CharField(default='', max_length=100)),
                ('Catchwords', models.TextField(default='')),
                ('Link', models.URLField(default='', max_length=100)),
                ('PDFLink', models.URLField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CitationSupplementModel',
            fields=[
                ('Bibliography', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='CitationSupplementModel', serialize=False, to='DecisionsPlus.BibliographyLanguageVersionModel')),
                ('CitedCases_NotInDB', models.TextField(default='')),
                ('TextCited_inDB', models.TextField(default='')),
                ('TextCited_NotInDB', models.TextField(default='')),
                ('BibliographyCiting', models.TextField(default='')),
                ('TextCiting', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='TextModel',
            fields=[
                ('Bibliography', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='TextModel', serialize=False, to='DecisionsPlus.BibliographyLanguageVersionModel')),
                ('FactsHeader', models.TextField(default='')),
                ('Facts', models.TextField(default='')),
                ('ReasonsHeader', models.TextField(default='')),
                ('Reasons', models.TextField(default='')),
                ('OrderHeader', models.TextField(default='')),
                ('Order', models.TextField(default='')),
                ('HasSplitText', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bibliographylanguageversionmodel',
            name='BibliographyBase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LanguageModel', to='DecisionsPlus.BibliographyBaseModel'),
        ),
    ]
